name: Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build-release:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{github.workspace}}/build
          
      - name: Install scdoc needed for manpage
        run: |
          sudo apt-get update && sudo apt-get install scdoc

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake -S .. -B . -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: |
          cmake --build . --config $BUILD_TYPE --target ydotool
          cmake --build . --config $BUILD_TYPE --target ydotoold

      - name: Rename build files
        run: |
          mv ${{github.workspace}}/build/ydotool ${{github.workspace}}/build/ydotool-release-${{matrix.os}}
          mv ${{github.workspace}}/build/ydotoold ${{github.workspace}}/build/ydotoold-release-${{matrix.os}}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.os}} build artifact
          path: |
            ${{github.workspace}}/build/ydotool-release-${{matrix.os}}
            ${{github.workspace}}/build/ydotoold-release-${{matrix.os}}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{github.workspace}}/build/ydotool-release-${{matrix.os}}
            ${{github.workspace}}/build/ydotoold-release-${{matrix.os}}
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

